batch_size: 32
dataset: rosbank
device: cuda
experiment_name: performer_len_100_run_1
lr: 0.001
max_length: 100
min_length: 20
n_epochs: 50
type: performer
transformer_params:
  dim_feedforward: 128
  dropout: 0.1
  feature_embeddings:
    amount_rur_bin: !!python/tuple
    - 11
    - 64
    small_group: !!python/tuple
    - 345
    - 64
  head_hidden: 128
  linear_proj: 64
  n_head: 8
  num_layers: 6
performer_params:
  dim_head: 32
  local_attn_heads: 0
  local_window_size: 256
  ff_mult: 4
  feature_redraw_interval: 1000
  reversible: False
  ff_chunks: 1
  generalized_attention: False
  use_scalenorm: False
  use_rezero: False
  ff_glu: False
  cross_attend: False
  no_projection: False
  auto_check_redraw: True
  qkv_bias: True
  attn_out_bias: True
  shift_tokens: False
warmup: 10
save_path: checkpoint