batch_size: 32
dataset: rosbank
device: cuda:1
experiment_name: reformer_2__run_01
lr: 0.001
max_length: 100
min_length: 20
n_epochs: 50
type: reformer
model_params:
  feature_embeddings:
    amount_rur_bin: !!python/tuple
    - 11
    - 64
    small_group: !!python/tuple
    - 345
    - 64
  linear_proj: 64
  n_head: 8
  n_local_attn_heads: 2
  dim_feedforward: 128
  dropout: 0.1
  num_layers: 6
  bucket_size: 10
  n_hashes: 4
  head_hidden: 128
warmup: 10
save_path: checkpoint