batch_size: 32
dataset: sberbank
device: cuda
experiment_name: performer2_len_1000_run_70
lr: 0.001
max_length: 1000
min_length: 20
n_epochs: 5
type: performer
transformer_params:
  dim_feedforward: 128
  dropout: 0.1
  feature_embeddings:
    amount_rur_bin: !!python/tuple
    - 11
    - 64
    small_group: !!python/tuple
    - 345
    - 64
  head_hidden: 128
  linear_proj: 64
  n_head: 8
  num_layers: 6
reformer_params:
  dim_feedforward: 64
  dropout: 0.1
  bucket_size: 25
  n_head: 8
  pkm_layers: [4,7]
  feature_embeddings:
    amount_rur_bin: !!python/tuple
    - 11
    - 64
    small_group: !!python/tuple
    - 345
    - 64
  head_hidden: 128
  linear_proj: 64
  num_layers: 8
performer_params:
  dim_head: 32
  local_heads: 0
  local_window_size: 256
  feature_redraw_interval: 100
  no_projection: True
  qkv_bias: False
  attn_out_bias: False
warmup: 10
save_path: checkpoint