batch_size: 32
dataset: rosbank
device: cuda
experiment_name: reformer2_len_100_run_70
lr: 0.001
max_length: 100
min_length: 20
n_epochs: 50
type: reformer
transformer_params:
  dim_feedforward: 128
  dropout: 0.1
  feature_embeddings:
    amount_rur_bin: !!python/tuple
    - 11
    - 64
    small_group: !!python/tuple
    - 345
    - 64
  head_hidden: 128
  linear_proj: 64
  n_head: 8
  num_layers: 6
reformer_params:
  attn_chunks: 1
  n_local_attn_heads: 4
  bucket_size: 10
  n_hashes: 4
  dim_head: 64
  random_rotations_per_head: True
  attend_across_buckets: True
  allow_duplicate_attention: False
  num_mem_kv: 0
  one_value_head: False
performer_params:
  dim_head: 32
  local_heads: 0
  local_window_size: 256
  feature_redraw_interval: 100
  no_projection: True
  qkv_bias: False
  attn_out_bias: False
warmup: 10
save_path: checkpoint